/**
 * # Configurable Azure Governance Module
 *
 * This module is based on the Cloud Adoption Frameworks Enterprise Scale Landingzone.
 * You can customize the management group layout, assigned policies and AAD groups to create and assign.
 * 
 * Use the archetype_lib folder in this repo to add custom archetypes, policy definitions and policy assignments.
 */

terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = ">= 2.77.0"
    }
    azuread = {
      source  = "hashicorp/azuread"
      version = "~> 2.15.0"
    }
  }
}

data "azurerm_client_config" "current" {}
data "azurerm_subscription" "subs" {
    for_each = local.sub_ids
    subscription_id = each.key
}

resource "azuread_group" "groups" {
    for_each = var.group_assignments
    display_name = each.key
    description = "Automatically generated by terraform: %{for role_desc in local.group_desc[each.key] ~}${role_desc}%{endfor ~}"
    security_enabled = true
    assignable_to_role = contains(var.pim_enabled_groups, each.key)
}

resource "azurerm_role_assignment" "role_assignments" {
  for_each = local.group_role_assignments
  scope                = each.value.scope
  role_definition_name = each.value.role_definition_name
  role_definition_id   = each.value.role_definition_id
  principal_id         = azuread_group.groups[each.value.principal].object_id
  depends_on           = [module.governance_eslz]
}

resource "azuread_application" "apps" {
  for_each = local.new_service_principals
  display_name = each.key
}

resource "azuread_service_principal" "sp" {
  for_each = local.new_service_principals
  application_id = azuread_application.apps[each.key].application_id
}

resource "azuread_group_member" "sp-assignments" {
  for_each = local.service_principal_assignments
  group_object_id  = azuread_group.groups[each.value.group].id
  member_object_id = azuread_service_principal.sp[each.value.service_principal].id
}

module "governance_eslz" {
  source  = "Azure/caf-enterprise-scale/azurerm"
  version = "5.0.3"

  providers = {
    azurerm              = azurerm
    azurerm.management   = azurerm
    azurerm.connectivity = azurerm
  }

  default_location = var.default_location

  root_parent_id   = data.azurerm_client_config.current.tenant_id
  root_id = local.caf_root_id

  deploy_core_landing_zones   = false
  deploy_corp_landing_zones   = false
  deploy_online_landing_zones = false
  deploy_sap_landing_zones    = false

  deploy_connectivity_resources = false
  deploy_identity_resources     = false
  deploy_management_resources   = false
  
  disable_telemetry = true
  
  custom_landing_zones            = local.caf_input
  template_file_variables         = var.template_file_variables
  strict_subscription_association = true
  library_path                    = var.library_path
}
